global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'telegram-webhook'
receivers:
 - name: alert
   webhook_configs:
   - send_resolved: True
     url: http://127.0.0.1:9087/alert/539686084
