version: '0.2'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    build: ./prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    restart: always
    deploy:
      mode: global
  
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards:./dashboards
    env_file:
      - config.monitoring

  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
     volumes:
      - ./blackboxexporter/:/etc/blackboxexporter/  
    command:
      - '--config.file=/etc/blackboxexporter/config.yml'
    restart: always
